[package]
name = "notifications"
version.workspace = true
edition.workspace = true

[dependencies]
shared = { workspace = true }
tokio = { workspace = true }
axum = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
rdkafka = { workspace = true }
tracing = { workspace = true }
opentelemetry = { workspace = true }
